[package]
name = "factory_method"
version = "0.1.0"
authors = ["Pick1a1username <20301273+Pick1a1username@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
roxmltree = "0.6.0"
